# @server = http://127.0.0.1:3030

@server = https://store-vifn.onrender.com
@api = {{server}}/v1
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWYiOiI2NWVlYTAxNDU2NDIwOTdjOTAzZGYyYWEiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxMDEzNzM4MSwiZXhwIjoxNzk2NTM3MzgxLCJhdWQiOiJ3ZWItdXNlciIsImlzcyI6InN0b3JlLWRldmVsb3BtZW50In0.hh307CrVpyjkoynV0Mdbp7b1WPXPjZRN3rMfTf2Ipyk

###
GET {{server}}

### ==== User Authentication =====

### sign up
POST {{api}}/auth/signup
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Daoa",
    "email": "wajix25578@fashlend.com",
    "password": "passirdhs",
    "phoneNo": "09066541174"
}

### sign in
POST {{api}}/auth/signin
Content-Type: application/json

{
    "email": "zuydudedr@gmail.com",
    "password": "passirdhs"
}

### forgot password
POST {{api}}/auth/forgot-password
Content-Type: application/json

{
    "email": "wajix25578@fashlend.com"
}

### verify otp
POST {{api}}/auth/verify-otp 
Content-Type: application/json

{
    "email": "zuydudedri@gufum.com",
    "code": "b3610c",
    "otpPurpose": "reset_password"
}

### resend otp
POST {{api}}/auth/resend-otp
Content-Type: application/json

{
    "email": "wajix25578@fashlend.com",
    "otpPurpose": "reset_password"
}

### reset password
PATCH  {{api}}/auth/reset-password
Content-Type: application/json

{
    "email": "zuydudedri@gufum.com",
    "password": "password2",
    "confirmPassword": "password2",
    "code": "b3610c"
}

### Products

### create product
POST {{api}}/product
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "haaiou",
    "category": "accessories",
    "description": "hh wjsf dmhaie, ssg",
    "price": 100.79,
    "quantityInStock": 40

}

### edit product
PUT {{api}}/product
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productId": "65edd0dd9d83584a19a8f8e7",
    "name": "hamdwu",
    "category": "accessories",
    "description": "hh wyksf jsfg",
    "price": 20.79,
    "quantityInStock": 1
    
}

### delete product
DELETE {{api}}/product/65edd0dd9d83584a19a8f8e7
Content-Type: application/json
Authorization: Bearer {{token}}

### search product
GET {{api}}/product?productId=65edd1eabad46656e6f2750a
Authorization: Bearer {{token}}


###  ========= Payment ==========

### initiate payment
POST {{api}}/tx/payment
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "idempotencyKey": "143uhvgwiy2amgf24iwl",
    "productId": "65edd1eabad46656e6f2750a",
    "currency": "NGN",
    "quantity": 2
}
