@server = http://127.0.0.1:3030
@api = {{server}}/v1
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWYiOiI2NWVkYzU0MGI5NDIzNzBkZjU0NWVmNTYiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxMDA4MjAzMiwiZXhwIjoxNzk2NDgyMDMyLCJhdWQiOiJ3ZWItdXNlciIsImlzcyI6InN0b3JlLWRldmVsb3BtZW50In0.xNu3faHR_3nGJqk5j63ILgGQtFpewQBSpcaiNWJ2lDg

###
GET {{server}}

### ==== User Authentication =====

### sign up
POST {{api}}/auth/signup
Content-Type: application/json

{
    "firstName": "Johssafn",
    "lastName": "Daorea",
    "email": "zuydudedri@gufum.com",
    "password": "passirdhs",
    "phoneNo": "09066541174"
}

### sign in
POST {{api}}/auth/signin
Content-Type: application/json

{
    "email": "zuydudedri@gufum.com",
    "password": "password2"
}

### forgot password
POST {{api}}/auth/forgot-password
Content-Type: application/json

{
    "email": "zuydudedri@gufum.com"
}

### verify otp
POST {{api}}/auth/verify-otp 
Content-Type: application/json

{
    "email": "zuydudedri@gufum.com",
    "code": "b3610c",
    "otpPurpose": "reset_password"
}

### resend otp
POST {{api}}/auth/resend-otp
Content-Type: application/json

{
    "email": "zuydudedri@gufum.com",
    "otpPurpose": "reset_password"
}

### reset password
PATCH  {{api}}/auth/reset-password
Content-Type: application/json

{
    "email": "zuydudedri@gufum.com",
    "password": "password2",
    "confirmPassword": "password2",
    "code": "b3610c"
}

### Products

### create product
POST {{api}}/product
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "hamdwu",
    "category": "accessories",
    "description": "hh wyksf jsfg",
    "price": 20.79,
    "quantityInStock": 2,

}

### edit product
PUT {{api}}/product
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productId": "",
    "name": "hamdwu",
    "category": "accessories",
    "description": "hh wyksf jsfg",
    "price": 20.79,
    "quantityInStock": 2,
    
}

### delete product
DELETE {{api}}/product
Content-Type: application/json
Authorization: Bearer {{token}}

### search product
GET {{api}}/product
Content-Type: application/json
Authorization: Bearer {{token}}


###  ========= Payment ==========

### initiate payment
POST {{api}}/tx/payment
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "idempotencyKey": "143uhvg24iwl",
    "productId": "",
    "currency": "USD",
    "quantity": 2
}