version: "3"
services:
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongoDb:/data/db

  api:
    build: .
    ports:
      - "6000:6000"
    env_file:
      .env
    volumes:
      - .:/usr/src/index
    depends_on:
      - mongo_db

volumes:
  mongoDb: {}
